// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/check-version": {
            "get": {
                "description": "This API endpoint checks the versions of E-commerce Payment Gateway data for two URLs constructed from a provided base URL in *ENV*.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "epg"
                ],
                "summary": "Check EPG Versions",
                "responses": {
                    "200": {
                        "description": "success response containing versions for both URLs",
                        "schema": {
                            "$ref": "#/definitions/checkversion.EPGVersionsResponse"
                        }
                    },
                    "400": {
                        "description": "on invalid request body",
                        "schema": {
                            "$ref": "#/definitions/constants.HttpError"
                        }
                    },
                    "500": {
                        "description": "on check version function error",
                        "schema": {
                            "$ref": "#/definitions/checkversion.EPGVersionsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "checkversion.EPGVersionsResponse": {
            "type": "object",
            "properties": {
                "error1": {
                    "type": "string"
                },
                "error2": {
                    "type": "string"
                },
                "version1": {
                    "type": "string"
                },
                "version2": {
                    "type": "string"
                }
            }
        },
        "constants.HttpError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
